#!/usr/bin/env python3
"""Build the embedded Modem Watchdog dashboard from normal web assets."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


CSS_TAG = "<link rel='stylesheet' href='/app.css'>"
JS_TAG = "<script src='/app.js'></script>"


def c_string_lines(text: str) -> str:
    """Encode UTF-8 source text as adjacent C string literals."""
    parts = text.splitlines(keepends=True)
    if not parts:
        parts = [""]
    return "\n".join(f"    {json.dumps(part, ensure_ascii=False)}" for part in parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--web-dir", required=True, type=Path)
    parser.add_argument("--out-html", required=True, type=Path)
    parser.add_argument("--out-header", required=True, type=Path)
    args = parser.parse_args()

    index = (args.web_dir / "index.html").read_text(encoding="utf-8")
    css = (args.web_dir / "app.css").read_text(encoding="utf-8").strip()
    js = (args.web_dir / "app.js").read_text(encoding="utf-8").strip()

    if CSS_TAG not in index:
        raise SystemExit(f"missing CSS placeholder: {CSS_TAG}")
    if JS_TAG not in index:
        raise SystemExit(f"missing JS placeholder: {JS_TAG}")

    bundled = index.replace(CSS_TAG, f"<style>\n{css}\n</style>")
    bundled = bundled.replace(JS_TAG, f"<script>\n{js}\n</script>")

    args.out_html.parent.mkdir(parents=True, exist_ok=True)
    args.out_header.parent.mkdir(parents=True, exist_ok=True)

    args.out_html.write_text(bundled, encoding="utf-8")
    header = (
        "/* Generated by tools/build_dashboard.py. Do not edit. */\n"
        "#pragma once\n\n"
        "static const char DASHBOARD_HTML[] =\n"
        f"{c_string_lines(bundled)};\n\n"
        "#define DASHBOARD_HTML_LEN (sizeof(DASHBOARD_HTML) - 1)\n"
    )
    args.out_header.write_text(header, encoding="utf-8")


if __name__ == "__main__":
    main()
